name: Deploy FastAPI to Docker with ngrok

on:
  push:
    branches:
      - release/dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # temporarily solution before hosting manually

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/deployment-test-app:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/deployment-test-app:latest

      - name: Create Docker network
        run: docker network create app-network

      - name: Run Docker container
        run: |
          docker run -d --network app-network --name deployment-test ${{ secrets.DOCKER_HUB_USERNAME }}/deployment-test-app:latest
          docker ps -a
          sleep 5

      - name: Install ngrok
        run: |
          curl -Lo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok.zip
          chmod +x ngrok

      - name: Start ngrok and keep tunnel alive
        run: |
          ./ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ./ngrok http deployment-test:8000 --url=horribly-suited-mongrel.ngrok-free.app &
          
          while true; do
            if ! curl -s http://localhost:4040/api/tunnels > /dev/null; then
              echo "Ngrok tunnel failed, exiting..."
              exit 1
            fi
            echo "Tunnel active at: $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
            sleep 300
          done

      - name: Get ngrok public URL
        run: |
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'