name: Deploy FastAPI to Docker with ngrok

on:
  push:
    branches:
      - release/dev

jobs:
  build-and-deploy: # names of the jobs
    runs-on: ubuntu-latest #the job run on the latest version of Ubuntu provided by GitHub Actions. This is a virtual machine with various tools and software pre-installed.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/deployment-test-app:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/deployment-test-app:latest

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name deployment-test ${{ secrets.DOCKER_HUB_USERNAME }}/deployment-test-app:latest
          docker ps -a
          sleep 5
          
      - name: Start ngrok
        uses: luisboto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 1h
          port: 8000
          ngrok_authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
          tunnel_type: http
          save_url_to_filename: tunnelURL.md

      - name: Get ngrok URL
        run: curl http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
